when@dev: &dev
    zenstruck_foundry:
        enable_auto_refresh_with_lazy_objects: true
        persistence:
            # Flush only once per call of `PersistentObjectFactory::create()`
            flush_once: true
        instantiator:
            use_constructor: false
            always_force_properties: true


when@test: *dev
